name: Scrape Airbnb Dubai (limite temps + anti-doublons)
on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.40.0

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper (time-bounded)
        run: |
          python scrape_airbnb.py

      - name: Upload RUN CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: airbnb-dubai-run
          path: airbnb_listings_run.csv

      - name: Commit & push MASTER CSV
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add airbnb_listings_master.csv || true
          git diff --cached --quiet || git commit -m "Update master CSV (time-bounded run)"
          git push || true
